#!/bin/bash
#Intento de script para parsear pruebas en la arquitectura


while getopts "h" opt
do
	case $opt in
	h) echo "Usage: First argument should be the config file in XML, and the results files must be in the current directory"
	esac
done
CONFIG=$1
SEARCH=*results*
for result in $SEARCH
do
	echo  $result >temp
	for a in $(xmllint --xpath "//conf/row" $CONFIG|sed -e 's/<row>//g' -e 's/<\/row>/ /g')
	do
		echo $a >cabecera
		grep  $a $result|sed -e "s/$a://g" > temp2
		cat cabecera temp2 > temp3
		cat temp3| tr -d '\n' >> temp4
		echo >> temp4
	done
	cat temp temp4 >> final
	rm temp* cabecera
done
