#!/bin/bash
#Intento de script para parsear pruebas en la arquitectura
SEARCH=*results*.txt
usage(){
	echo "Usage: First argument should be the config file in XML, and the results files must be in the current directory"
}

TEMP=`getopt -o h --long help \
     -n "$0" -- "$@"`
eval set -- "$TEMP"
while true
do
	case "$1" in
		-h|--help) usage; exit 0;;
		--) shift; break;;
	esac
done
if [ -z $1 ]; then echo "Falta el archivo de configuración del parseator" && exit 1 ; fi
CONFIG=$1
mkdir -p resultados
PROPERTIES=$(xmllint --xpath "//conf/row" $CONFIG | sed -e 's/<row>//g' -e 's/<\/row>/ /g')
for result in $SEARCH
do
	TESTS=$(cat $result |	grep -c $(xmllint --xpath "//conf/row" $CONFIG | sed -e 's/<row>//g' -e 's/<.*$//g'))
	break
done
for result in $SEARCH
do
	rm -f $result.xml
	RESULT=$(cat $result)
	echo -n "$result start: "
	date;
	for test in `seq 0 $TESTS`
	do
		echo -n "$test start: "
		date
		for property in $PROPERTIES
		do
			if [ 0 -eq $test ]; then
				a=`echo $RESULT | grep $property | sed -n -e "1 p" | sed -e "s/: .*//"`
			else
				a=`echo $RESULT | grep $property | sed -n -e "$test p" | sed -e "s/.*: //"`
			fi
			echo -n "$a " >> $result.xml
		done
		echo "" >> $result.xml
		echo -n "$test end: "
		date
	done
	echo -n "$result end: "
	date;
done
